// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UNISchedule.DataAccess;

#nullable disable

namespace UNISchedule.DataAccess.Migrations
{
    [DbContext(typeof(UniScheduleDbContext))]
    [Migration("20250519211201_InitialIdentityAndProfiles")]
    partial class InitialIdentityAndProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.ClassTimeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ClassTimeEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.ClassroomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Building")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassroomEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstituteEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstituteEntityId");

                    b.ToTable("GroupEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.InstituteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("InstituteEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.ScheduleRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ClassTimeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassroomEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("SubjectAssignmentEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassTimeEntityId");

                    b.HasIndex("ClassroomEntityId");

                    b.HasIndex("SubjectAssignmentEntityId")
                        .IsUnique();

                    b.ToTable("ScheduleRecordEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.StudentProfileEntity", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("StudentProfileEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.SubjectAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleRecordEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherProfileEntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TypeSubjectEntityID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupEntityId");

                    b.HasIndex("SubjectEntityId");

                    b.HasIndex("TeacherProfileEntityId");

                    b.HasIndex("TypeSubjectEntityID");

                    b.ToTable("SubjectAssignmentEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.SubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SubjectEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.TeacherProfileEntity", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("InstituteEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("InstituteEntityId");

                    b.HasIndex("InstituteId");

                    b.ToTable("TeacherProfileEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.TypeSubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TypeSubjectEntities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.GroupEntity", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.InstituteEntity", "InstituteEntity")
                        .WithMany("Groups")
                        .HasForeignKey("InstituteEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstituteEntity");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.ScheduleRecordEntity", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.ClassTimeEntity", "ClassTime")
                        .WithMany("ScheduleRecordEntities")
                        .HasForeignKey("ClassTimeEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.ClassroomEntity", "ClassroomEntity")
                        .WithMany("ScheduleRecordEntities")
                        .HasForeignKey("ClassroomEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.SubjectAssignmentEntity", "SubjectAssignmentEntity")
                        .WithOne("ScheduleRecordEntitis")
                        .HasForeignKey("UNISchedule.DataAccess.Entities.ScheduleRecordEntity", "SubjectAssignmentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTime");

                    b.Navigation("ClassroomEntity");

                    b.Navigation("SubjectAssignmentEntity");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.StudentProfileEntity", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne("StudentProfile")
                        .HasForeignKey("UNISchedule.DataAccess.Entities.StudentProfileEntity", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.GroupEntity", "Group")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.SubjectAssignmentEntity", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.GroupEntity", "GroupEntity")
                        .WithMany("SubjectAssignments")
                        .HasForeignKey("GroupEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.SubjectEntity", "SubjectEntity")
                        .WithMany("SubjectAssignmentEntities")
                        .HasForeignKey("SubjectEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.TeacherProfileEntity", "TeacherProfileEntity")
                        .WithMany("subjectAssignmentEntities")
                        .HasForeignKey("TeacherProfileEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.TypeSubjectEntity", "TypeSubjectEntity")
                        .WithMany("SubjectAssignmentEntities")
                        .HasForeignKey("TypeSubjectEntityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupEntity");

                    b.Navigation("SubjectEntity");

                    b.Navigation("TeacherProfileEntity");

                    b.Navigation("TypeSubjectEntity");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.TeacherProfileEntity", b =>
                {
                    b.HasOne("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("UNISchedule.DataAccess.Entities.TeacherProfileEntity", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNISchedule.DataAccess.Entities.InstituteEntity", null)
                        .WithMany("TeacherProfiles")
                        .HasForeignKey("InstituteEntityId");

                    b.HasOne("UNISchedule.DataAccess.Entities.InstituteEntity", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.ClassTimeEntity", b =>
                {
                    b.Navigation("ScheduleRecordEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.ClassroomEntity", b =>
                {
                    b.Navigation("ScheduleRecordEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.GroupEntity", b =>
                {
                    b.Navigation("StudentProfiles");

                    b.Navigation("SubjectAssignments");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.InstituteEntity", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("TeacherProfiles");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.SubjectAssignmentEntity", b =>
                {
                    b.Navigation("ScheduleRecordEntitis")
                        .IsRequired();
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.SubjectEntity", b =>
                {
                    b.Navigation("SubjectAssignmentEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.TeacherProfileEntity", b =>
                {
                    b.Navigation("subjectAssignmentEntities");
                });

            modelBuilder.Entity("UNISchedule.DataAccess.Entities.TypeSubjectEntity", b =>
                {
                    b.Navigation("SubjectAssignmentEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
